driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_version: current

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
- name: debian-8
  driver:
    image: debian:8
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install apt-transport-https lsb-release procps net-tools -y

- name: centos-6
  driver:
    image: centos:6
    platform: rhel
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN yum -y install lsof which initscripts net-tools wget net-tools

- name: centos-7
  driver:
    image: centos:7
    platform: rhel
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN yum -y install lsof which systemd-sysv initscripts wget net-tools

- name: fedora-latest
  driver:
    image: fedora:latest
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN dnf -y install which systemd-sysv initscripts wget net-tools

- name: ubuntu-14.04
  driver:
    image: ubuntu-upstart:14.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install apt-transport-https lsb-release procps net-tools -y

- name: ubuntu-16.04
  driver:
    image: ubuntu:16.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install apt-transport-https lsb-release procps net-tools -y

- name: opensuse-leap
  driver:
    image: opensuse:leap
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN zypper --non-interactive install aaa_base perl-Getopt-Long-Descriptive which net-tools

suites:
- name: default
  run_list:
  - recipe[ssh_known_hosts_test]
  attributes: {}
- name: default-query
  run_list:
  - recipe[ssh_known_hosts_test]
  attributes:
    ssh_known_hosts:
      node_query_search: 'AND chef_environment:stage'
- name: cacher
  run_list:
  - recipe[ssh_known_hosts_test::cacher]
  attributes: {}
- name: cacher-client
  run_list:
  - recipe[ssh_known_hosts_test::default]
  attributes:
    ssh_known_hosts:
      use_data_bag_cache: true
- name: resource
  run_list:
  - recipe[ssh_known_hosts_test::resource]
